# .goreleaser.yml
# Build customization
rust:
- target:
  - x86_64-apple-darwin
  binary: hello

# Archive customization
archive:
  format: tar.gz
  replacements:
    amd64: 64-bit
    darwin: macOS
    linux: Tux
  files:
    - drum-roll.licence.txt